version: '3.0'

rpc:
    listen: tcp://0.0.0.0:6001

server:
    command: "php app.php"
    relay: pipes

logs:
    level: info

centrifuge:
    proxy_address: "tcp://0.0.0.0:10001"
    grpc_api_address: "centrifugo:10000"
    pool:
        num_workers: 2

metrics:
    address: 0.0.0.0:2112

status:
    address: 127.0.0.1:2114
    unavailable_status_code: 503

otel:
    insecure: true
    compress: false
    client: http
    exporter: otlp
    service_name: rr-centrifugo
    service_version: 1.0.0
    endpoint: collector:4318
